/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IAgentPayOS {
    function registerService(string calldata name, uint256 price, address token) external returns (bytes32);

    function deactivateService(bytes32 service_id) external;

    function reactivateService(bytes32 service_id) external;

    function approveAgent(address agent, uint256 allowance, uint256 duration_seconds) external;

    function payForService(address user, bytes32 service_id) external;

    function computeSessionKey(address user, address agent) external view returns (bytes32);
}
